spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

#  main:
#    web-application-type: none

  cloud:
    config:
      enabled: true

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true




info:
  app:
    name: "gatewayserver"
    description: "API gateway server for FinStream Application"
    version: "1.0.0"

logging:
  level:
    com:
      finStream:
        finstreamapigateway: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000